### ISSUE TITLE
why is it called anolog and not analog?

### ISSUE THREAD

**Issue by juggledad** [meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi#1]
Just wondering why the node name is an**o**log and not an**a**log?

**Comment by meeki007** [comment]
Because I made a typo. And I'd have to release another package on NPM if I
change the name :)
However I will go back and change the title and keywords its found under
but the package name will have to stay the same.

Good find,
Thankyou,

David

**Comment by meeki007** [comment]
Closed
