### ISSUE TITLE
Hard to use payload object key.

### ISSUE THREAD

**Issue by fjbruwer** [meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi#10]
The Key for the returned object is long, contains spaces and special formatting and non-obvious values that can change between implementations. This makes it difficult to retrieve the voltage from the object.

A better solution might be to create separate fields in the object, i.e:
{ "voltage" : 1.5 , "bus" : "i2c1", "ADC":2, ...}

**Comment by fjbruwer** [comment]
`diff --git a/ads1x15.js b/ads1x15.js
index f653fc8..5e190b5 100644
--- a/ads1x15.js
+++ b/ads1x15.js
@@ -146,7 +146,10 @@ module.exports = function(RED)
                                 //put all msgs into a object
                                 var voltage_output_object =
                                 {
-                                    [[this.chip.slice(this.chip.length - 7)] + " • " + ["I2C_" + [this.i2c_address]]  + " • " + "Channel " + ["A" + [this.channel.slice(this.channel.length - 1)] + "-GND"] + " • " + "Voltage"]:volts
+                                    "voltage":volts,
+                                    "channel":["A" + [this.channel.slice(this.channel.length - 1)] + "-GND"],
+                                    "address":this.i2c_address,
+                                    "chip":[this.chip.slice(this.chip.length - 7)]
                                 };
 
                                 //send to volts to payload
`

**Comment by fjbruwer** [comment]
[simplify_payload.txt](https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/files/5885930/simplify_payload.txt)

**Comment by meeki007** [comment]
Agree! 
will work on it
see this post ---> [https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/issues/11](https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/issues/11)

**Comment by meeki007** [comment]
see changes here. new version is pushed to npm as well. update the node and I hope this helps. 

https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/pull/12/files

**Comment by fjbruwer** [comment]
Thanks, appreciate the effort, I'll check it out this afternoon
