### ISSUE TITLE
Thanks for a nice Node !

### ISSUE THREAD

**Issue by MatsA** [meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi#11]
and good documentation, not that common ;-) 
But agree with @fjbruwer that it is hard to use the payload object. I'm not good enough in JS to do a PR. 
Thanks ! 

Thera are certainly other better solutions but this is mine
// {"ADS1015 • I2C_ADDRESS_0x48 • Channel A0-GND • Voltage":0.5682774792379092}
let x = JSON.stringify(msg.payload)
let y = x.search(":");                  // node.warn(y)
let z = x.substring(y + 1, y + 11);
msg.payload = parseFloat(z)

instead of just msg.payload = msg.payload.voltage

**Comment by meeki007** [comment]
Agreed ! 
I put off fixing this for so long but it is hard to use the message.
I'll look into this now for 1hr and then put some time in this weekend on cleaning up the msg

**Comment by meeki007** [comment]
see changes here. new version is pushed to npm as well. update the node and I hope this helps. 

https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/pull/12/files

**Comment by MatsA** [comment]
Thanks ! Nice !
