### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by agalianos** [meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi#2]
I am getting the message:
"Unable to connect to ADC and Failed to fetch value from Chipset:IC_ADS1115 CHANNEL_0 ADDRESS_0x48"
What might be wrong?

**Comment by meeki007** [comment]
It is most likely the ADC is not connected to the I2c channel you using.
Please make sure the ADC Is connected to the device.

this might help you: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c

**Comment by meeki007** [comment]
Any news ? did you fix the issue ?

**Comment by meeki007** [comment]
No Response from user in 5 days ......closing issue.
