### ISSUE TITLE
Wrong channel measurement

### ISSUE THREAD

**Issue by ArnePaul** [meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi#7]
When using the sample from the web with all 4 channels in use, I get a measurement for a wrong channel. I applied a voltage to channel A1, but the values returned was shown as channel A2. When using only A1 as a single channel it seems to work, but the first measurement after deploying shows zero and the following measurements are ok.
![Error](https://user-images.githubusercontent.com/66468249/83861742-43b64700-a721-11ea-85c4-b1945ec33c60.png)

**Comment by meeki007** [comment]
Bad timing. I am wrapping up a contract I'm on and will be in the Smokey mountains for a month June 13th to July 17th When I get back I can take a look at the issue and patch. I will have spotty internet when I go to town ...etc. so I can check in.  

Sorry.

**Comment by meeki007** [comment]
Closing issue. It is now grouped into this issue --- > [https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/issues/8](https://github.com/meeki007/node-red-contrib-anolog-to-digital-converter-raspberry-pi/issues/8)
